### ISSUE TITLE
support for HW with Serial > 001-2700

### ISSUE THREAD

**Issue by dm9876** [bwoodill/BT_VESC#12]
Hi there, just wondering if there is any plan or possibility to support this hardware? Thanks!

**Comment by bwoodill** [comment]
It is supported. Only lower than 001-2700 isn't.

**Comment by dm9876** [comment]
Thanks for your response. The readme currently says the opposite

**Comment by bwoodill** [comment]
That is because you are looking at the master branch which is not compatible. Fred and George branches are the versions that work on higher SN (depending on what you have). The last release has builds for each version. You have to determine which version your scooter currently has to determine which file to use.

**Comment by dm9876** [comment]
Thankyou I missed that you had alternative branches. Appreciate your work on this project!

**Comment by adrianbill** [comment]
Hi,
Thanks @bwoodill for the amazing work.

I wanted to add that think it would be beneficial to mention the different versions available in each readme. Just like you have in the release section.  The fact that the Master Readme states that isn't compatible with higher serial numbers is confusing. I made the same mistake as @dm9876.

I think some thing like this would be very helpful:

## WARNING
Make sure to choose the correct branch for your scooter.

1. Check the serial number of the scooter
    -  If your scooter's serial number is **LOWER** than "001-2700" use the Master branch
    -  Otherwise follow the next steps
2. Open the VESC tool
3. Connect to your scooter
4. Go to the terminal
5. Run `$$`
    - If output shows `v1.19` use the "v2.3_FRED_1.19" branch.
    - If output shows `GEORGE VERSION 0.4` then use the "v2.3_GEORGE_0.4" branch
